---
driver:
  name: vagrant
  require_chef_omnibus: true
  provider: virtualbox
  vm_hostname: ntp.local

provisioner:
  name: chef_zero
  clients_path: test/fixtures/clients
  data_bags_path: test/fixtures/data_bags
  environments_path: test/fixtures/environments
  nodes_path: test/fixtures/nodes
  roles_path: test/fixtures/roles
  encrypted_data_bag_secret_key_path: test/fixtures/data_bags/encrypted_data_bag_secret


platforms:

- name: centos-7
  driver_config:
    box: local/centos7
    box_url: ~/Development/Vagrant/Boxes/centos7.box

suites:
- name: default
  provisioner:
    client_rb:
      environment: testing
  run_list:
    - recipe[ntp::default]
  attributes: {}
