---
driver:
  name: vagrant
  require_chef_omnibus: true
  provider: virtualbox
  vm_hostname: ntp.local

provisioner:
  name: chef_zero
  clients_path: test/fixtures/clients
  data_bags_path: test/fixtures/data_bags
  environments_path: test/fixtures/environments
  nodes_path: test/fixtures/nodes
  roles_path: test/fixtures/roles
  encrypted_data_bag_secret_key_path: test/fixtures/data_bags/encrypted_data_bag_secret


platforms:

- name: centos6.5
  driver_config:
    box: inf24/centos6.5
    box_url: ~/IT/Vagrant/Boxes/opscode_centos-6.5_chef-provisionerless.box

- name: centos7
  driver_config:
    box: inf24/centos7
    box_url: ~/IT/Vagrant/Boxes/opscode_centos-7.0_chef-provisionerless.box

- name: sles11sp1
  driver_config:
    box: inf24/sles11sp1
    box_url: ~/IT/Vagrant/Boxes/sles-11sp1-x64-vbox4210.box

- name: sles11sp3
  driver_config:
    box: inf24/sles11sp3
    box_url: ~/IT/Vagrant/Boxes/sles11sp3.box



suites:
- name: default
  provisioner:
    client_rb:
      environment: testing
  run_list:
    - recipe[ntp::default]
  attributes: {}
